var language = navigator.languages?navigator.languages[0]:navigator.language||navigator.userLanguage;language=language.substring(0,2); "denesfrit".indexOf(language)>=0||(language="en"); 
var source = "{{#each this}}<section><time>{{pt b}} - {{pt a}}</time>{{#each m}}<div class='stages'><h1 class='{{mode}} {{rule}}'>{{tr rule}}</h1>{{#each stages}}<figure><img src='i/{{id}}.png'><figcaption>{{tr id}}</figcaption></figure>{{/each}}</div>{{/each}}</section>{{/each}}";
var r = function() { Handlebars.registerHelper("pt", function(time) {return moment(time).format("HH:mm")}); Handlebars.registerHelper("tr", function(name) {return messages[language][name]}); var template = Handlebars.compile(source); document.body.innerHTML = template(stages) }; document.addEventListener('DOMContentLoaded',r);
var messages = {
de : {am:"Arowana-Center",bd:"Blauflossen-Depot",bs:"Punkasius-Skatepark",ct:"Camp Schützenfisch",fh:"Schollensiedlung",kd:"Tümmlerkuppel",mt:"Muränentürme",pm:"Heilbutt-Hafen",sr:"Bohrinsel Nautilus",uu:"Dekabahnstation",ww:"Kofferfisch-Lager",fest:"Splatfestkampf",rain:"Operation Goldfisch",rank:"Rangkampf",regular:"Standardkampf",splat:"Herrschaft",tower:"Turm-Kommando",turf:"Revierkampf"},
en : {am:"Arowana Mall",bd:"Bluefin Depot",bs:"Blackbelly Skatepark",ct:"Camp Triggerfish",fh:"Flounder Heights",kd:"Kelp Dome",mt:"Moray Towers",pm:"Port Mackerel",sr:"Saltspray Rig",uu:"Urchin Underpass",ww:"Walleye Warehouse",fest:"Splatfest Battle",rain:"Rainmaker",rank:"Ranked Battle",regular:"Regular Battle",splat:"Splat Zones",tower:"Tower Control",turf:"Turf War"},
es : {am:"Plazuela del Calamar",bd:"Mina costera",bs:"Parque Lubina",ct:"Campamento Arowana",fh:"Complejo Medusa",kd:"Jardín botánico",mt:"Torres Merluza",pm:"Puerto Jurel",sr:"Plataforma Gaviota",uu:"Parque Viaducto",ww:"Almacén Rodaballo",fest:"Combate temático",rain:"Pez dorado",rank:"Combate competitivo",regular:"Combate amistoso",splat:"Pintazonas",tower:"Torreón",turf:"Territorial"},
fr : {am:"Centre Arowana",bd:"Mine marine",bs:"Skatepark Mako",ct:"Hippo-Camping",fh:"Lotissement Filament",kd:"Serre Goémon",mt:"Tours Girelle",pm:"Docks Haddock",sr:"Station Doucebrise",uu:"Passage Turbot",ww:"Encrepôt",fest:"Festimatch",rain:"Mission Bazookarpe",rank:"Match pro",regular:"Match classique",splat:"Défense de zone",tower:"Expédition risquée",turf:"Guerre de territoire"},
it : {am:"Centro commerciale",bd:"Molo Mollusco",bs:"Pista Polposkate",ct:"Campeggio Totan",fh:"Cime Sogliolose",kd:"Serra di alghe",mt:"Torri cittadine",pm:"Porto Polpo",sr:"Raffineria",uu:"Periferia urbana",ww:"Magazzino",fest:"Partita tematica",rain:"Operazione Pesce d'oro",rank:"Partita pro",regular:"Partita amichevole",splat:"Zona splat",tower:"Torre mobile",turf:"Mischie mollusche"}
};