#!/bin/sh
export TERM=xterm-256color
r=`lsb_release -sd`
k=`uname -srmo`
p=`wget -q -O - http://ipv4.icanhazip.com/ | tail`
h=`hostname -f`
a=`hostname -i | cut -d " " -f 2`
d=`df -h  | grep root | awk {'print "total " $2 "	free " $4 "	used " $3 " (" $5 ")"'}`
m=`free -h | grep Mem | awk {'print "total " $2 "	free " $7 "	used " $3'}`
l=`cat /proc/loadavg`
u=`uptime -p | sed s/up.//`

BG='\033[1;31m'
BR='\033[0;33m'
CY='\033[1;36m'
DG='\033[1;30m'
NG='\033[0;32m'
NR='\033[0;31m'
PU='\033[1;35m'
RS='\033[0m'

echo "
$BR  .==================.  $RS
$BR  | .--------------. |  $NG $r - $k
$BR  | |$CY--.__.--.__.--$BR| |  $RS
$BR  | |$PU--.__.--.__.--$BR| |  $NR hostname........: $BG$h
$BR  | |$CY--.__.--.__.--$BR| |  $NR addresses.......: $CY$a$NR and $PU$p
$BR  | |$PU--.__.--.__.--$BR| |  $NR disk............: $d
$BR  | |$CY--.__.--.__.--$BR| |  $NR memory..........: $m
$BR  | '--------------' |  $NR load ...........: $l
$BR  |  $DG##    ()    ##$BR  |  $NR uptime..........: $u
$BR  '=================='  $RS
"

