#!/bin/sh
export TERM=xterm-256color
r=`lsb_release -sd`
k=`uname -srmo`
p=`wget -q -O - http://ipv4.icanhazip.com/ | tail`
h=`hostname -f`
a=`hostname -i | cut -d " " -f 2`
d=`df -h  | grep root | awk {'print "total " $2 "	free " $4 "	used " $3 " (" $5 ")"'}`
m=`free -h | grep Mem | awk {'print "total " $2 "	free " $7 "	used " $3'}`
l=`uptime | cut -d , -f 4,5,6 | cut -d : -f 2`
u=`uptime -p | sed s/up.//`

cpu=$(cut -c 1,2 /sys/class/thermal/thermal_zone0/temp)
gpu=$(/opt/vc/bin/vcgencmd measure_temp | cut -c 7,6)
t="CPU ${cpu}° C	GPU ${gpu}° C"

BG='\033[1;32m'
BR='\033[1;31m'
CY='\033[1;36m'
NG='\033[0;32m'
NR='\033[0;31m'
PU='\033[1;35m'
RS='\033[0m'
YE='\033[1;33m'


echo "
$BG      .~~.   .~~.       $RS
$BG     '. \ ' ' / .'      $NG $r - $k
$BR      .~ .~~~..~.       $RS
$BR     : .~.'~'.~. :      $NR hostname........: $BR$h
$BR    ~ (   ) (   ) ~     $NR addresses.......: $CY$a$NR and $PU$p
$BR   ( : '~'.~.'~' : )    $NR disk............: $d
$BR    ~ .~ (   ) ~. ~     $NR memory..........: $m
$BR     (  : '~' :  )      $NR temperature.....: $YE$t
$BR      '~ .~~~. ~'       $NR uptime..........: $u	load$l
$BR          '~'           $RS
"
